<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>MigrationKit.Ambiguity</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$(GymShared)MockServer\Gym.MockServer\Gym.MockServer.csproj" />
  </ItemGroup>
</Project>
